"""Add transaction storage

Revision ID: 41102b67cc37
Revises: 5a30dfccba79
Create Date: 2026-04-27 02:27:15.781744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41102b67cc37"
down_revision: str | Sequence[str] | None = "5a30dfccba79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_cycle",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "start_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "end_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cycle_snapshot",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("activity_score", sa.Integer(), nullable=False),
        sa.Column("bonus_score", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(team_id IS NULL) != (user_id IS NULL)",
            name="check_cycle_snapshot_owner_xor",
        ),
        sa.ForeignKeyConstraint(["cycle_id"], ["game_cycle.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cycle_snapshot_cycle_id"), "cycle_snapshot", ["cycle_id"], unique=False
    )
    op.create_index(
        op.f("ix_cycle_snapshot_team_id"), "cycle_snapshot", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_cycle_snapshot_user_id"), "cycle_snapshot", ["user_id"], unique=False
    )
    op.create_table(
        "point_transaction",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(team_id IS NULL) != (user_id IS NULL)",
            name="check_point_transaction_owner_xor",
        ),
        sa.ForeignKeyConstraint(["cycle_id"], ["game_cycle.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_point_transaction_cycle_id"),
        "point_transaction",
        ["cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_point_transaction_team_id"),
        "point_transaction",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_point_transaction_user_id"),
        "point_transaction",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_point_transaction_user_id"), table_name="point_transaction")
    op.drop_index(op.f("ix_point_transaction_team_id"), table_name="point_transaction")
    op.drop_index(op.f("ix_point_transaction_cycle_id"), table_name="point_transaction")
    op.drop_table("point_transaction")
    op.drop_index(op.f("ix_cycle_snapshot_user_id"), table_name="cycle_snapshot")
    op.drop_index(op.f("ix_cycle_snapshot_team_id"), table_name="cycle_snapshot")
    op.drop_index(op.f("ix_cycle_snapshot_cycle_id"), table_name="cycle_snapshot")
    op.drop_table("cycle_snapshot")
    op.drop_table("game_cycle")
    # ### end Alembic commands ###
