"""Move logic to postgres

Revision ID: 4f4474ac6b7c
Revises: e2d127b9bd90
Create Date: 2026-04-06 00:32:11.006761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f4474ac6b7c"
down_revision: str | Sequence[str] | None = "e2d127b9bd90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "student_profile",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "team",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )

    op.execute("""
        CREATE OR REPLACE FUNCTION format_user_email() RETURNS TRIGGER AS $$
        BEGIN
            NEW.email = LOWER(NEW.email);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_format_user_email
        BEFORE INSERT OR UPDATE ON "user"
        FOR EACH ROW EXECUTE FUNCTION format_user_email();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION format_student_names() RETURNS TRIGGER AS $$
        BEGIN
            NEW.first_name = INITCAP(NEW.first_name);
            NEW.last_name = INITCAP(NEW.last_name);
            IF NEW.patronymic IS NOT NULL THEN
                NEW.patronymic = INITCAP(NEW.patronymic);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_format_student_names
        BEFORE INSERT OR UPDATE ON student
        FOR EACH ROW EXECUTE FUNCTION format_student_names();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_format_student_names ON student;")
    op.execute("DROP FUNCTION IF EXISTS format_student_names();")
    op.execute("DROP TRIGGER IF EXISTS trg_format_user_email ON user;")
    op.execute("DROP FUNCTION IF EXISTS format_user_email();")

    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "team",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "student_profile",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "student",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
