"""Move logic to postgres

Revision ID: 4f4474ac6b7c
Revises: e2d127b9bd90
Create Date: 2026-04-06 00:32:11.006761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f4474ac6b7c"
down_revision: str | Sequence[str] | None = "e2d127b9bd90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column(
            "full_name",
            sa.String(length=255),
            sa.Computed(
                "last_name || ' ' || first_name || COALESCE(' ' || patronymic, '')",
                persisted=True,
            ),
            nullable=False,
        ),
    )

    op.alter_column(
        "student",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "student_profile",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "team",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )

    op.create_check_constraint(
        constraint_name="chk_phone_format",
        table_name="student_profile",
        condition="phone_number ~ '^\\+[1-9]\\d{1,14}$'",
    )
    op.create_check_constraint(
        constraint_name="chk_student_id_digits",
        table_name="student",
        condition="student_id ~ '^[0-9]+$'",
    )
    op.create_check_constraint(
        constraint_name="chk_valid_email",
        table_name="user",
        condition="email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'",
    )

    op.execute("""
        CREATE OR REPLACE FUNCTION format_user_email() RETURNS TRIGGER AS $$
        BEGIN
            NEW.email = LOWER(NEW.email);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_format_user_email
        BEFORE INSERT OR UPDATE ON "user"
        FOR EACH ROW EXECUTE FUNCTION format_user_email();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION format_student_names() RETURNS TRIGGER AS $$
        BEGIN
            NEW.first_name = INITCAP(NEW.first_name);
            NEW.last_name = INITCAP(NEW.last_name);
            IF NEW.patronymic IS NOT NULL THEN
                NEW.patronymic = INITCAP(NEW.patronymic);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_format_student_names
        BEFORE INSERT OR UPDATE ON student
        FOR EACH ROW EXECUTE FUNCTION format_student_names();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_format_student_names ON student;")
    op.execute("DROP FUNCTION IF EXISTS format_student_names();")
    op.execute("DROP TRIGGER IF EXISTS trg_format_user_email ON user;")
    op.execute("DROP FUNCTION IF EXISTS format_user_email();")

    op.drop_constraint("chk_phone_format", "student_profile", type_="check")
    op.drop_constraint("chk_student_id_digits", "student", type_="check")
    op.drop_constraint("chk_valid_email", "user", type_="check")

    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "team",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "student_profile",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "student",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )

    op.drop_column("student", "full_name")
    # ### end Alembic commands ###
