"""Fix media owner not unique

Revision ID: 505904dda5b8
Revises: e9c538589b20
Create Date: 2026-05-10 22:32:16.177552

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "505904dda5b8"
down_revision: str | Sequence[str] | None = "e9c538589b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.create_index(op.f("ix_media_owner_id"), "media", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.create_index(op.f("ix_media_owner_id"), "media", ["owner_id"], unique=True)
    # ### end Alembic commands ###
