"""Transaction snapshot decimal values

Revision ID: 77af3e4c651a
Revises: c5e5988e3f67
Create Date: 2026-05-12 01:37:14.378359

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77af3e4c651a"
down_revision: str | Sequence[str] | None = "c5e5988e3f67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cycle_snapshot",
        "activity_score",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=8, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "cycle_snapshot",
        "bonus_score",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=8, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "cycle_snapshot",
        "total_score",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=8, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cycle_snapshot",
        "total_score",
        existing_type=sa.Numeric(precision=8, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "cycle_snapshot",
        "bonus_score",
        existing_type=sa.Numeric(precision=8, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "cycle_snapshot",
        "activity_score",
        existing_type=sa.Numeric(precision=8, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
