"""Add market models

Revision ID: b2e040a563cd
Revises: 6d9f23c22f2d
Create Date: 2026-05-12 23:21:29.304542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2e040a563cd"
down_revision: str | Sequence[str] | None = "6d9f23c22f2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_listing",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("game_cycle_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["game_cycle_id"], ["game_cycle.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_listing_author_id"),
        "market_listing",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_listing_game_cycle_id"),
        "market_listing",
        ["game_cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_listing_team_id"), "market_listing", ["team_id"], unique=False
    )
    op.create_table(
        "market_response",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("responder_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("market_listing_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="marketresponsestatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_listing_id"], ["market_listing.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["responder_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_response_market_listing_id"),
        "market_response",
        ["market_listing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_response_responder_id"),
        "market_response",
        ["responder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_response_team_id"), "market_response", ["team_id"], unique=False
    )
    op.create_index(
        "uq_market_response_one_accepted_per_listing",
        "market_response",
        ["market_listing_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.create_table(
        "market_deal",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("market_response_id", sa.Uuid(), nullable=False),
        sa.Column(
            "report_id", sa.Uuid(), server_default=sa.text("NULL"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", name="marketdealstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_response_id"], ["market_response.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_deal_market_response_id"),
        "market_deal",
        ["market_response_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_market_deal_report_id"), "market_deal", ["report_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_deal_report_id"), table_name="market_deal")
    op.drop_index(op.f("ix_market_deal_market_response_id"), table_name="market_deal")
    op.drop_table("market_deal")
    op.drop_index(
        "uq_market_response_one_accepted_per_listing",
        table_name="market_response",
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.drop_index(op.f("ix_market_response_team_id"), table_name="market_response")
    op.drop_index(op.f("ix_market_response_responder_id"), table_name="market_response")
    op.drop_index(
        op.f("ix_market_response_market_listing_id"), table_name="market_response"
    )
    op.drop_table("market_response")
    op.drop_index(op.f("ix_market_listing_team_id"), table_name="market_listing")
    op.drop_index(op.f("ix_market_listing_game_cycle_id"), table_name="market_listing")
    op.drop_index(op.f("ix_market_listing_author_id"), table_name="market_listing")
    op.drop_table("market_listing")
    # ### end Alembic commands ###
