"""Points type column for transaction

Revision ID: c5e5988e3f67
Revises: 505904dda5b8
Create Date: 2026-05-12 00:08:07.787443

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5e5988e3f67"
down_revision: str | Sequence[str] | None = "505904dda5b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    point_type_enum = sa.Enum("BONUS", "ACTIVITY", name="pointtype")
    point_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "point_transaction",
        sa.Column(
            "points_type",
            sa.Enum("BONUS", "ACTIVITY", name="pointtype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point_transaction", "points_type")
    point_type_enum = sa.Enum("BONUS", "ACTIVITY", name="pointtype")
    point_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
