"""Add media storage

Revision ID: e9c538589b20
Revises: 41102b67cc37
Create Date: 2026-05-10 19:25:54.360852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9c538589b20"
down_revision: str | Sequence[str] | None = "41102b67cc37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_table(
        "media",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_owner_id"), "media", ["owner_id"], unique=True)
    op.create_index(
        "ix_student_search_vector_trgm",
        "student",
        [
            sa.text(
                "(student_id || ' ' || first_name || ' ' || "
                + "last_name || ' ' || coalesce(patronymic, '')) gin_trgm_ops"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_student_search_vector_trgm",
        table_name="student",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
